### ISSUE TITLE
Validation is not working?

### ISSUE THREAD

**Issue by erpriliano** [emrade/flutter-cool-stepper#5]
Hi, 

I'm building a form using `DropdownButton` widget and `TextFormField` without using `Form()` widget and its built-in validation because I assume I can code validation function inside your `CoolStepper` widget. I know your `validation` property will return `String`, so I've made this code:

```dart
CoolStep(
title: 'Informasi Kendaraan',
subtitle: 'Silahkan isi dengan informasi umum kendaraan anda',
validation: () {
  if (brand == null) {
    return 'Pilih merk kendaraan anda';
  } else {
    return null;
  }
},
content: Column(
  children: [
    Container(
      margin: const EdgeInsets.symmetric(horizontal: 5.0),
      child: DropdownButton<String>(
        autofocus: true,
        items: brands.map((String brand) {
          return new DropdownMenuItem(
            value: brand,
            child: Text(brand, style: TextStyle(fontSize: 14),),
          );
        }).toList(),
        onChanged: _onBrandChanged,
        value: brand,
        hint: Text('Pilih merk', style: TextStyle(fontSize: 14),),
        isExpanded: true,
      ),
    ),
. . .
```
when I ran the code and didn't select any of the **brand** value, nothing happened. I thought the return String will show somewhere inside my applications. So what's the right way to do validation inside your `CoolStep` widget?

**Comment by emrade** [comment]
Hello, I had initially added a toast to show when validation failed but
some people did not want it, and after thinking about it too I figured that
the toast might not adhere to the theme which the user is working on. So I
removed the toast message.

But basically, what the validation is there for is just so you can stop the
stepper from moving to the next step.

I wanted a method people were already familiar with which is why I made it
look like how TextField handles its validation.

So if you wanna display an error message or something, inside your if
clause you could just trigger the error to show yourself.

I hope I have given you a satisfactory answer.

Thanks.

**Comment by erpriliano** [comment]
Okay, but I've an idea, rather than adding a toast to show the validation why don't you add a snackbar instead, it's more appropriate and also more adhere to the any theme used by the users. But if you want to play it safe why don't you give users something to show validation rather than we're using flutter's TextField built in validation method? Because at the end, your widget will be used more in form which is why we need something to show its validation...

Hope this can be a good idea for your improvement

**Comment by emrade** [comment]
@erpriliano Thanks a lot for your feedback and suggestion.

I just released a new update for the package cool_stepper: ^1.1.3

I added a new property called 'showErrorSnackbar'. it's default value is false, its meant to show errors via a snackbar if it is set to true. So you could just set it to true.

I hope that helped.
