### ISSUE TITLE
Why must progLabels have the same number as there are steps?

### ISSUE THREAD

**Issue by FaridAhamat** [emrade/flutter-cool-stepper#6]
The progLabels must be declared with the same number of elements as there are steps, which is kinda... odd, because the last one would always uses the 'finalText'. For example, if there are 3 steps, I would declare the progLabels such that:

      config: CoolStepperConfig(
        backText: "PREV",
        finalText: "Complete!",
        progLabels: [ "Test1", "Test2", "Test3" ]
      ),

The first step would use the "Test2", so why do I need to declare "Test1"?

**Comment by emrade** [comment]
@FaridAhamat You can try the latest version of the package cool_stepper: ^1.1.3

I removed the progLabels and introduced two new properties 'backTextList' and 'nextTextList'.

The backTextList is a string list and is meant to override the backText, the length must be one less than the number of steps since for the first step, the backText won't be visible.

The nextTextList is also a string list and is meant to override the nextText, the length must be one less than the number of steps since the 'finalText' attribute is able to set the value for the final step's next button.

I hope this helps. If it does not, feel free to repopen the issue
